title: Stellamaris W. Nakacwa # your name (or website title) here

logo: "https://github.com/StellaWava/StellaWava.github.io/blob/core/images/stellamaris3.jpg?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  A Research Scientist with 6 years of experience and exceptional abilities in computational analytics, geospatial data science, big data engineering, and distributed systems as a utility. 
  Vastly exposed to various data ecosystems through a variety of projects including; Energy, agricultural, and policy data. 
  A Master's degree in Geography from WVU, Eberly College of Arts & Sciences, and currently pursuing a MSc. Computational & Applied Mathematics.
  Previously a Program Director, ESM YouthMappers, a USAID Program, developing both maps and the next generation of geospatial workforce. 
  
  AWS Certified Cloud Practitioner 
  <a href="https://www.linkedin.com/in/stellawava/">View My LinkedIn Profile </a> 
  <a href="https://www.researchgate.net/profile/Stellamaris-Nakacwa/research">Find My Publications Here</a> 

theme: jekyll-theme-minimal
google_analytics: none  # your Google Analytics tracking ID here

colors:
  crimson: '#900C3F'
