title: Stellamaris W Nakacwa # your name (or website title) here
#logo: "/images/linkedin.jpg?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  <br>
  Research Scientist with over 5 years of expertise in computational analytics, geospatial analysis, data science, engineering, and distributed systems as a utility. 
  Extensive experience in energy data and international data processing. Holds a Master's degree in Geography from West Virginia University, Eberly College of Arts & Sciences.
  Previously at YouthMappers, a USAID Program, developing both maps and the next generation of mappers. 
  <br><br>
  AWS Certified Cloud Practitioner 
  <br><br>
  <a href="https://www.linkedin.com/in/stellawava">View my LinkedIn Profile</a> 
  <a href="https://www.researchgate.net/profile/Stellamaris-Nakacwa/research">Find my Publications here</a> 
theme: jekyll-theme-minimal
google_analytics: none  # your Google Analytics tracking ID here

colors:
  crimson: '#900C3F'
